name: PrintFresh Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Login test
      run: npm run test:Login
    - name: Search, Add to Cart Test
      run: npm run test:Search
    - name: Summer Shop Nav tests
      run: npm run test:Summer
    - name: New Items test
      run: npm run test:New
    - name: Best Sellers Nav tests
      run: npm run test:BestSellers
    - name: Lounge Nav tests
      run: npm run test:Lounge
    - name: Apparel Nav tests
      run: npm run test:Apparel
    - name: Luxe Nav tests
      run: npm run test:Luxe
    - name: Accessories Nav tests
      run: npm run test:Accessories

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
